datasets:
  - name: ventes
    path: resources/ventes_*.parquet
    expectation_suite: ventes
    checkpoint_name: ventes_checkpoint

  - name: clients_databricks
    type: databricks
    table: demo_edadou.gold.bv_customer_order
    expectation_suite: bv_orders
    checkpoint_name: bv_orders_checkpoint